name: Sync changes to GitLab

on:
  push:
    branches: [main]

jobs:
  build:
    if: (github.repository == 'KudoAI/bravegpt')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout KudoAI/bravegpt
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Push changes to gitlab.com/kudoai/bravegpt
        env:
          GITLAB_SYNC_PAT: ${{ secrets.GITLAB_SYNC_PAT }}
        run: |
          git push --force -o ci.skip \
            https://oauth2:$GITLAB_SYNC_PAT@gitlab.com/kudoai/bravegpt.git main
